version: '3'

services:
  discord:
    container_name: zettaibot
    build: .
    volumes:
      - .:/usr/src/app
      - ./assets/pics:/usr/src/app/assets/pics
      - ./assets/audio:/usr/src/app/assets/audio
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npx nodemon